from tkinter import BOTH, BOTTOM, CENTER, END, HORIZONTAL, NONE, RIGHT, X, Y


class Styles:
    WHITE_COLOR = "#FFFFFF"
    BLACK_COLOR = "#000000"

    FONT_ARIAL = "Arial"
    FONT_ARIAL_10 = f"{FONT_ARIAL} 10"

    FONT_ROBOTO = "Roboto"
    FONT_ROBOTO_10 = f"{FONT_ROBOTO} 10"
    FONT_ROBOTO_12 = f"{FONT_ROBOTO} 12"
    FONT_ROBOTO_13 = f"{FONT_ROBOTO} 13"
    FONT_ROBOTO_14 = f"{FONT_ROBOTO} 14"
    FONT_ROBOTO_15 = f"{FONT_ROBOTO} 15"
    FONT_ROBOTO_20 = f"{FONT_ROBOTO} 20"

    WRAP_NONE = NONE

    FILL_BOTH = BOTH
    FILL_Y = Y
    FILL_X = X

    SIDE_RIGHT = RIGHT
    SIDE_BOTTOM = BOTTOM

    ORIENT_HORIZONTAL = HORIZONTAL

    POSITION_END = END

    ANCHOR_CENTER = CENTER
