from tkinter import BOTH, BOTTOM, CENTER, END, HORIZONTAL, NONE, RIGHT, X, Y

FONT_ARIAL = "Arial"
FONT_ROBOTO = "Roboto"
FONT_ARIAL_10 = f"{FONT_ARIAL} 10"
FONT_ROBOTO_10 = f"{FONT_ROBOTO} 10"

WRAP_NONE = NONE

FILL_BOTH = BOTH
FILL_Y = Y
FILL_X = X

SIDE_RIGHT = RIGHT
SIDE_BOTTOM = BOTTOM

ORIENT_HORIZONTAL = HORIZONTAL

POSITION_END = END

ANCHOR_CENTER = CENTER
